http:
  ip: "0.0.0.0"
  port: 2000
grpc:
  host: "0.0.0.0"
  port: 5001
log:
  log_file: application.log
  log_level: debug
db:
  user: root
  password: password
  port: 5435
  host: "127.0.0.1"
#  host: DB_HOST
#  port: ${DB_PORT:5432}
  database: calendar
ampq:
#  host: "calendar-rabbit"
  host: "127.0.0.1"
  port: 5672
  user: root
  password: password
  queue: events_queue
scheduler:
  period: 360
  before_time: 60
  event_time: 60
